sudo: false
language: ruby
rvm:
  - 2.5.5
  - 2.7.2
gemfile:
  - gemfiles/jr0.9.gemfile
env:
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"
  - "RAILS_VERSION=6.1.0"

before_install: gem install bundler -v 1.17.3
